### ISSUE TITLE
Non-GPL Image

### ISSUE THREAD

**Issue by Foggalong** [Capuno/Farfetch#5]
What was the outcome of the image being non-GPL? Was the [leagal info](https://github.com/Capuno/Farfetch/commit/dc0c42f01ada40158e9393ba037d50f36273c29b#diff-04c6e90faac2675aa89e2176d2eec7d8) disclaimer all that was required?

**Comment by Capuno** [comment]
Everyone I asked told me I could use it as fair use since it's just a link to the art in the readme, and the name has nothing to do with it (I got the idea from **far** faster **fetch**).
I sent an email to the pokèmon copyright team and I will leave the disclaimer temporarily until I get a response.
